## Sigmoid Function

In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# sigmoid activation function 
def sigmoid(x):
    return 1/(1 + np.exp(-x))

## Implementation of Multilayer Perceptron

In [3]:
#define weights and bias as w and b, x is input array, lastly 'a' being the node
x = np.array([0.5, 1])
w1 = np.array([[0.1, 0.2, 0.15], [0.6, 0.2, 0.8]]) 
b1 = np.array([0.1, 0.2, 0.05])

In [4]:
#calculate the dot product and sum with bias 
a1 = np.dot(x, w1) + b1
a1

array([0.75 , 0.5  , 0.925])

In [5]:
#calculate the activation function for a1
z1 = sigmoid(a1)
z1

array([0.6791787 , 0.62245933, 0.71605979])

In [6]:
#define the weights for second node 
w2 = np.array([[0.1, 0.2], [0.05, 0.5], [0.1, 0.2]])
w2

array([[0.1 , 0.2 ],
       [0.05, 0.5 ],
       [0.1 , 0.2 ]])

In [7]:
#define bias for second node 

b2 = np.array([0.4, 0.5])
b2

array([0.4, 0.5])

In [8]:
#calculate the dot product and sum with bias 
a2 = np.dot(z1, w2) + b2
a2

array([0.57064682, 1.09027736])

In [9]:
#calculate the activation function for a2

z2 = sigmoid(a2)
z2

array([0.63891241, 0.74843395])

In [10]:
#define weight and bias for second node 

w3 = np.array([[0.1, 0.2], [0.9, 0.8]])
b3 = np.array([0.9, 0.9])

In [11]:
#calculate the activation function
a3 = np.dot(z2, w3) + b3
a3

array([1.63748179, 1.62652964])

In [12]:
#calculate the activation function for a3
z3 = sigmoid(a3)
z3

array([0.83719199, 0.83569368])